version: "2"
services:
  adminer:
    image: asergey/adminer:latest
    container_name: koa.adminer
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASS: 1
    ports:
      - 3308:80
    links:
      - mysql
    logging:
      driver: none
  mysql:
    image: mysql:5.7.18
    container_name: koa.mysql
    ports:
      - 3307:3308
    environment:
      MYSQL_DATABASE: appdb
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 1
    logging:
      driver: none
